### ISSUE TITLE
Push not received

### ISSUE THREAD

**Issue by ramhoj** [chvanikoff/apns4ex#28]
This is a long-shot and might not be related to apns4ex at all so feel free to close it.

With that said we're experiencing problems with devices sometimes not receiving pushes we send. We can see that `:ssl.send/2` returns `:ok` (https://github.com/chvanikoff/apns4ex/blob/master/lib/apns/worker.ex#L277) for the token associated with the device that should have received the push. Other devices, on the same network, receives the same message (with a different APNS push token ofc) and the same device that didn't receive the push earlier has a good chance of receiving another push later.

We get no errors in the error callback or via the feedback service for the affected token. The problem isn't either connected to one specific APNS push token but seems to be random among all our stored tokens.

Do you know if there is any chance that `:ssl.send/2` can return `:ok` without the message actually being sent? Have you experienced anything similar?

**Comment by arkadiyk** [comment]
I am not sure if it is related, but I did have situation when `:ssl.send/2` returns `:ok` but the message has not been received. The error in the log appeared few minutes later and it was rather cryptic. 

In my case it was due to my company firewall was resetting the connection after 30 min of idle time. Somehow `:ssl.send/2` cannot detect that connection is closed and returns `:ok`

In `apsn4erl` this problem was solved by https://github.com/inaka/apns4erl/pull/54 ..

**Comment by ramhoj** [comment]
Thank you @arkadiyk! We believe our issue is with #29, do you know if apns4erl handles this?

**Comment by zepplock** [comment]
So is the issue here with SSL reconnect/timeout of is the real issue as described in #29?

**Comment by ramhoj** [comment]
@zepplock we think so. Let's close this issue in favor if #29
